/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './chips.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from 'primeng/components/chips/chips';
import * as import10 from 'primeng/components/dom/domhandler';
import * as import11 from '../../node_modules/primeng/components/chips/chips.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/forms/src/directives/control_value_accessor';
import * as import17 from '@angular/forms/src/directives/ng_model';
import * as import18 from '@angular/forms/src/directives/ng_control';
import * as import19 from '@angular/forms/src/directives/ng_control_status';
import * as import20 from '@angular/core/src/security';
export class Wrapper_ChipsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ChipsComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor() {
    this._changed = false;
    this.context = new import0.ChipsComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_index(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.index = currValue;
      this._expr_0 = currValue;
    }
  }
  check_clazzName(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.clazzName = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ChipsComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ChipsComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ChipsComponent>;
  _ChipsComponent_0_3:Wrapper_ChipsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChipsComponent_Host0,renderType_ChipsComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'chipsCrudRestful',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ChipsComponent0(this.viewUtils,this,0,this._el_0);
    this._ChipsComponent_0_3 = new Wrapper_ChipsComponent();
    this.compView_0.create(this._ChipsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ChipsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ChipsComponent) && (0 === requestNodeIndex))) { return this._ChipsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ChipsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ChipsComponentNgFactory:import8.ComponentFactory<import0.ChipsComponent> = new import8.ComponentFactory<import0.ChipsComponent>('chipsCrudRestful',View_ChipsComponent_Host0,import0.ChipsComponent);
const styles_ChipsComponent:any[] = ([] as any[]);
var renderType_ChipsComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_ChipsComponent,{});
export class View_ChipsComponent0 extends import2.AppView<import0.ChipsComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import2.AppView<import9.Chips>;
  _DomHandler_11_3:import10.DomHandler;
  _Chips_11_4:import11.Wrapper_Chips;
  _NG_VALUE_ACCESSOR_11_5:any[];
  _NgModel_11_6:import12.Wrapper_NgModel;
  _NgControl_11_7:any;
  _NgControlStatus_11_8:import13.Wrapper_NgControlStatus;
  _query_PrimeTemplate_11_0:import14.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChipsComponent0,renderType_ChipsComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_23 = import1.UNINITIALIZED;
    this._expr_24 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'    \n                ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_3,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','col-md-10'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'    \n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'p-chips',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_11 = new import11.View_Chips0(this.viewUtils,this,11,this._el_11);
    this._DomHandler_11_3 = new import10.DomHandler();
    this._Chips_11_4 = new import11.Wrapper_Chips(new import15.ElementRef(this._el_11),this._DomHandler_11_3);
    this._NG_VALUE_ACCESSOR_11_5 = [this._Chips_11_4.context];
    this._NgModel_11_6 = new import12.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_5);
    this._NgControl_11_7 = this._NgModel_11_6.context;
    this._NgControlStatus_11_8 = new import13.Wrapper_NgControlStatus(this._NgControl_11_7);
    this._query_PrimeTemplate_11_0 = new import14.QueryList<any>();
    this.compView_11.create(this._Chips_11_4.context);
    this._text_12 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'            \n        ',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(6,'ngModelChange',(null as any),'onAdd',(null as any),'onRemove',(null as any)),this.eventHandler(this.handleEvent_11));
    this._Chips_11_4.subscribe(this,this.eventHandler(this.handleEvent_11),true,true);
    this._NgModel_11_6.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DomHandler) && (11 === requestNodeIndex))) { return this._DomHandler_11_3; }
    if (((token === import9.Chips) && (11 === requestNodeIndex))) { return this._Chips_11_4.context; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_5; }
    if (((token === import17.NgModel) && (11 === requestNodeIndex))) { return this._NgModel_11_6.context; }
    if (((token === import18.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_7; }
    if (((token === import19.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_8.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_11_0_0:any = this.context.disabled;
    this._Chips_11_4.check_disabled(currVal_11_0_0,throwOnChange,false);
    this._Chips_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = this.context.disabled;
    this._NgModel_11_6.check_isDisabled(currVal_11_1_0,throwOnChange,false);
    const currVal_11_1_1:any = this.context.values;
    this._NgModel_11_6.check_model(currVal_11_1_1,throwOnChange,false);
    this._NgModel_11_6.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_8.ngDoCheck(this,this._el_11,throwOnChange);
    if (!throwOnChange) {
      if (this._query_PrimeTemplate_11_0.dirty) {
        this._query_PrimeTemplate_11_0.reset(([] as any[]));
        this._Chips_11_4.context.templates = this._query_PrimeTemplate_11_0;
        this._query_PrimeTemplate_11_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Chips_11_4.context.ngAfterContentInit(); }
    }
    const currVal_23:any = import3.inlineInterpolate(1,'',this.context.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setText(this._text_6,currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this.context.width;
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementStyle(this._el_11,'width',((this.viewUtils.sanitizer.sanitize(import20.SecurityContext.STYLE,currVal_24) == null)? (null as any): this.viewUtils.sanitizer.sanitize(import20.SecurityContext.STYLE,currVal_24).toString()));
      this._expr_24 = currVal_24;
    }
    this._NgControlStatus_11_8.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_11.destroy();
    this._Chips_11_4.ngOnDestroy();
    this._NgModel_11_6.ngOnDestroy();
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.values = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onAdd')) {
      const pd_sub_1:any = ((<any>this.context.add($event.value)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onRemove')) {
      const pd_sub_2:any = ((<any>this.context.remove($event.value)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}