/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from 'primeng/components/button/button';
import * as import10 from 'primeng/components/inputtext/inputtext';
import * as import11 from 'primeng/components/calendar/calendar';
import * as import12 from 'primeng/components/common/shared';
import * as import13 from 'primeng/components/dropdown/dropdown';
import * as import14 from 'primeng/components/checkbox/checkbox';
import * as import15 from 'primeng/components/slider/slider';
import * as import16 from 'primeng/components/inplace/inplace';
import * as import17 from 'primeng/components/inputmask/inputmask';
import * as import18 from 'primeng/components/tabview/tabview';
import * as import19 from 'primeng/components/confirmdialog/confirmdialog';
import * as import20 from 'primeng/components/paginator/paginator';
import * as import21 from 'primeng/components/datatable/datatable';
import * as import22 from 'primeng/components/multiselect/multiselect';
import * as import23 from 'primeng/components/panel/panel';
import * as import24 from 'primeng/components/tree/tree';
import * as import25 from 'primeng/components/togglebutton/togglebutton';
import * as import26 from 'primeng/components/inputswitch/inputswitch';
import * as import27 from 'primeng/components/accordion/accordion';
import * as import28 from 'primeng/components/chips/chips';
import * as import29 from './primeng.module';
import * as import30 from './crud.module';
import * as import31 from '@angular/common/src/localization';
import * as import32 from '@angular/core/src/application_init';
import * as import33 from '@angular/core/src/testability/testability';
import * as import34 from '@angular/core/src/application_ref';
import * as import35 from '@angular/core/src/linker/compiler';
import * as import36 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import37 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import38 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import39 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import40 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import41 from '@angular/core/src/animation/animation_queue';
import * as import42 from '@angular/core/src/linker/view_utils';
import * as import43 from '@angular/platform-browser/src/browser/title';
import * as import44 from '@angular/forms/src/form_builder';
import * as import45 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import46 from '@angular/http/src/backends/browser_xhr';
import * as import47 from '@angular/http/src/base_response_options';
import * as import48 from '@angular/http/src/backends/xhr_backend';
import * as import49 from '@angular/http/src/base_request_options';
import * as import50 from 'primeng/components/common/api';
import * as import51 from './examples/scheduling';
import * as import52 from './examples/user';
import * as import53 from '@angular/core/src/di/injector';
import * as import54 from './components/input.component.ngfactory';
import * as import55 from './components/multiselect.component.ngfactory';
import * as import56 from './components/chips.component.ngfactory';
import * as import57 from './components/select.component.ngfactory';
import * as import58 from '@angular/core/src/i18n/tokens';
import * as import59 from '@angular/core/src/application_tokens';
import * as import60 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import61 from '@angular/platform-browser/src/dom/events/key_events';
import * as import62 from '@angular/core/src/zone/ng_zone';
import * as import63 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import64 from '@angular/core/src/console';
import * as import65 from '@angular/core/src/error_handler';
import * as import66 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import67 from '@angular/platform-browser/src/dom/animation_driver';
import * as import68 from '@angular/core/src/render/api';
import * as import69 from '@angular/core/src/security';
import * as import70 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import71 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import72 from '@angular/http/src/interfaces';
import * as import73 from '@angular/http/src/http';
import * as import74 from '@angular/core/src/linker/view';
import * as import75 from '@angular/core/src/metadata/view';
import * as import76 from '@angular/core/src/linker/view_type';
import * as import77 from '@angular/core/src/change_detection/constants';
import * as import78 from '@angular/core/src/linker/component_factory';
import * as import79 from './crud.component';
import * as import80 from './services/service';
import * as import81 from './crud.component.ngfactory';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _ReactiveFormsModule_4:import6.ReactiveFormsModule;
  _FormsModule_5:import6.FormsModule;
  _HttpModule_6:import7.HttpModule;
  _RouterModule_7:import8.RouterModule;
  _ButtonModule_8:import9.ButtonModule;
  _InputTextModule_9:import10.InputTextModule;
  _CalendarModule_10:import11.CalendarModule;
  _SharedModule_11:import12.SharedModule;
  _DropdownModule_12:import13.DropdownModule;
  _CheckboxModule_13:import14.CheckboxModule;
  _SliderModule_14:import15.SliderModule;
  _InplaceModule_15:import16.InplaceModule;
  _InputMaskModule_16:import17.InputMaskModule;
  _TabViewModule_17:import18.TabViewModule;
  _ConfirmDialogModule_18:import19.ConfirmDialogModule;
  _PaginatorModule_19:import20.PaginatorModule;
  _DataTableModule_20:import21.DataTableModule;
  _MultiSelectModule_21:import22.MultiSelectModule;
  _PanelModule_22:import23.PanelModule;
  _TreeModule_23:import24.TreeModule;
  _ToggleButtonModule_24:import25.ToggleButtonModule;
  _InputSwitchModule_25:import26.InputSwitchModule;
  _AccordionModule_26:import27.AccordionModule;
  _ChipsModule_27:import28.ChipsModule;
  _PrimeNgModule_28:import29.PrimeNgModule;
  _CrudModule_29:import30.CrudModule;
  _AppModule_30:import1.AppModule;
  __LOCALE_ID_31:any;
  __NgLocalization_32:import31.NgLocaleLocalization;
  _ErrorHandler_33:any;
  _ApplicationInitStatus_34:import32.ApplicationInitStatus;
  _Testability_35:import33.Testability;
  _ApplicationRef__36:import34.ApplicationRef_;
  __ApplicationRef_37:any;
  __Compiler_38:import35.Compiler;
  __APP_ID_39:any;
  __DOCUMENT_40:any;
  __HAMMER_GESTURE_CONFIG_41:import36.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_42:any[];
  __EventManager_43:import37.EventManager;
  __DomSharedStylesHost_44:import38.DomSharedStylesHost;
  __AnimationDriver_45:any;
  __DomRootRenderer_46:import39.DomRootRenderer_;
  __RootRenderer_47:any;
  __DomSanitizer_48:import40.DomSanitizerImpl;
  __Sanitizer_49:any;
  __AnimationQueue_50:import41.AnimationQueue;
  __ViewUtils_51:import42.ViewUtils;
  __IterableDiffers_52:any;
  __KeyValueDiffers_53:any;
  __SharedStylesHost_54:any;
  __Title_55:import43.Title;
  __FormBuilder_56:import44.FormBuilder;
  __RadioControlRegistry_57:import45.RadioControlRegistry;
  __BrowserXhr_58:import46.BrowserXhr;
  __ResponseOptions_59:import47.BaseResponseOptions;
  __XSRFStrategy_60:any;
  __XHRBackend_61:import48.XHRBackend;
  __RequestOptions_62:import49.BaseRequestOptions;
  __Http_63:any;
  __ConfirmationService_64:import50.ConfirmationService;
  __Scheduling_65:import51.Scheduling;
  __User_66:import52.User;
  constructor(parent:import53.Injector) {
    super(parent,[
      import54.InputTextComponentNgFactory,
      import55.MultiSelectComponentNgFactory,
      import56.ChipsComponentNgFactory,
      import57.SelectComponentNgFactory,
      AppNgFactory
    ]
    ,[AppNgFactory]);
  }
  get _LOCALE_ID_31():any {
    if ((this.__LOCALE_ID_31 == null)) { (this.__LOCALE_ID_31 = import3._localeFactory(this.parent.get(import58.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_31;
  }
  get _NgLocalization_32():import31.NgLocaleLocalization {
    if ((this.__NgLocalization_32 == null)) { (this.__NgLocalization_32 = new import31.NgLocaleLocalization(this._LOCALE_ID_31)); }
    return this.__NgLocalization_32;
  }
  get _ApplicationRef_37():any {
    if ((this.__ApplicationRef_37 == null)) { (this.__ApplicationRef_37 = this._ApplicationRef__36); }
    return this.__ApplicationRef_37;
  }
  get _Compiler_38():import35.Compiler {
    if ((this.__Compiler_38 == null)) { (this.__Compiler_38 = new import35.Compiler()); }
    return this.__Compiler_38;
  }
  get _APP_ID_39():any {
    if ((this.__APP_ID_39 == null)) { (this.__APP_ID_39 = import59._appIdRandomProviderFactory()); }
    return this.__APP_ID_39;
  }
  get _DOCUMENT_40():any {
    if ((this.__DOCUMENT_40 == null)) { (this.__DOCUMENT_40 = import4._document()); }
    return this.__DOCUMENT_40;
  }
  get _HAMMER_GESTURE_CONFIG_41():import36.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_41 == null)) { (this.__HAMMER_GESTURE_CONFIG_41 = new import36.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_41;
  }
  get _EVENT_MANAGER_PLUGINS_42():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_42 == null)) { (this.__EVENT_MANAGER_PLUGINS_42 = [
      new import60.DomEventsPlugin(),
      new import61.KeyEventsPlugin(),
      new import36.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_41)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_42;
  }
  get _EventManager_43():import37.EventManager {
    if ((this.__EventManager_43 == null)) { (this.__EventManager_43 = new import37.EventManager(this._EVENT_MANAGER_PLUGINS_42,this.parent.get(import62.NgZone))); }
    return this.__EventManager_43;
  }
  get _DomSharedStylesHost_44():import38.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_44 == null)) { (this.__DomSharedStylesHost_44 = new import38.DomSharedStylesHost(this._DOCUMENT_40)); }
    return this.__DomSharedStylesHost_44;
  }
  get _AnimationDriver_45():any {
    if ((this.__AnimationDriver_45 == null)) { (this.__AnimationDriver_45 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_45;
  }
  get _DomRootRenderer_46():import39.DomRootRenderer_ {
    if ((this.__DomRootRenderer_46 == null)) { (this.__DomRootRenderer_46 = new import39.DomRootRenderer_(this._DOCUMENT_40,this._EventManager_43,this._DomSharedStylesHost_44,this._AnimationDriver_45,this._APP_ID_39)); }
    return this.__DomRootRenderer_46;
  }
  get _RootRenderer_47():any {
    if ((this.__RootRenderer_47 == null)) { (this.__RootRenderer_47 = import63._createConditionalRootRenderer(this._DomRootRenderer_46,this.parent.get(import63.NgProbeToken,(null as any)),this.parent.get(import34.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_47;
  }
  get _DomSanitizer_48():import40.DomSanitizerImpl {
    if ((this.__DomSanitizer_48 == null)) { (this.__DomSanitizer_48 = new import40.DomSanitizerImpl()); }
    return this.__DomSanitizer_48;
  }
  get _Sanitizer_49():any {
    if ((this.__Sanitizer_49 == null)) { (this.__Sanitizer_49 = this._DomSanitizer_48); }
    return this.__Sanitizer_49;
  }
  get _AnimationQueue_50():import41.AnimationQueue {
    if ((this.__AnimationQueue_50 == null)) { (this.__AnimationQueue_50 = new import41.AnimationQueue(this.parent.get(import62.NgZone))); }
    return this.__AnimationQueue_50;
  }
  get _ViewUtils_51():import42.ViewUtils {
    if ((this.__ViewUtils_51 == null)) { (this.__ViewUtils_51 = new import42.ViewUtils(this._RootRenderer_47,this._Sanitizer_49,this._AnimationQueue_50)); }
    return this.__ViewUtils_51;
  }
  get _IterableDiffers_52():any {
    if ((this.__IterableDiffers_52 == null)) { (this.__IterableDiffers_52 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_52;
  }
  get _KeyValueDiffers_53():any {
    if ((this.__KeyValueDiffers_53 == null)) { (this.__KeyValueDiffers_53 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_53;
  }
  get _SharedStylesHost_54():any {
    if ((this.__SharedStylesHost_54 == null)) { (this.__SharedStylesHost_54 = this._DomSharedStylesHost_44); }
    return this.__SharedStylesHost_54;
  }
  get _Title_55():import43.Title {
    if ((this.__Title_55 == null)) { (this.__Title_55 = new import43.Title()); }
    return this.__Title_55;
  }
  get _FormBuilder_56():import44.FormBuilder {
    if ((this.__FormBuilder_56 == null)) { (this.__FormBuilder_56 = new import44.FormBuilder()); }
    return this.__FormBuilder_56;
  }
  get _RadioControlRegistry_57():import45.RadioControlRegistry {
    if ((this.__RadioControlRegistry_57 == null)) { (this.__RadioControlRegistry_57 = new import45.RadioControlRegistry()); }
    return this.__RadioControlRegistry_57;
  }
  get _BrowserXhr_58():import46.BrowserXhr {
    if ((this.__BrowserXhr_58 == null)) { (this.__BrowserXhr_58 = new import46.BrowserXhr()); }
    return this.__BrowserXhr_58;
  }
  get _ResponseOptions_59():import47.BaseResponseOptions {
    if ((this.__ResponseOptions_59 == null)) { (this.__ResponseOptions_59 = new import47.BaseResponseOptions()); }
    return this.__ResponseOptions_59;
  }
  get _XSRFStrategy_60():any {
    if ((this.__XSRFStrategy_60 == null)) { (this.__XSRFStrategy_60 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_60;
  }
  get _XHRBackend_61():import48.XHRBackend {
    if ((this.__XHRBackend_61 == null)) { (this.__XHRBackend_61 = new import48.XHRBackend(this._BrowserXhr_58,this._ResponseOptions_59,this._XSRFStrategy_60)); }
    return this.__XHRBackend_61;
  }
  get _RequestOptions_62():import49.BaseRequestOptions {
    if ((this.__RequestOptions_62 == null)) { (this.__RequestOptions_62 = new import49.BaseRequestOptions()); }
    return this.__RequestOptions_62;
  }
  get _Http_63():any {
    if ((this.__Http_63 == null)) { (this.__Http_63 = import7.httpFactory(this._XHRBackend_61,this._RequestOptions_62)); }
    return this.__Http_63;
  }
  get _ConfirmationService_64():import50.ConfirmationService {
    if ((this.__ConfirmationService_64 == null)) { (this.__ConfirmationService_64 = new import50.ConfirmationService()); }
    return this.__ConfirmationService_64;
  }
  get _Scheduling_65():import51.Scheduling {
    if ((this.__Scheduling_65 == null)) { (this.__Scheduling_65 = new import51.Scheduling()); }
    return this.__Scheduling_65;
  }
  get _User_66():import52.User {
    if ((this.__User_66 == null)) { (this.__User_66 = new import52.User(this.parent.get(import52.string))); }
    return this.__User_66;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._ReactiveFormsModule_4 = new import6.ReactiveFormsModule();
    this._FormsModule_5 = new import6.FormsModule();
    this._HttpModule_6 = new import7.HttpModule();
    this._RouterModule_7 = new import8.RouterModule(this.parent.get(import8.ROUTER_FORROOT_GUARD,(null as any)));
    this._ButtonModule_8 = new import9.ButtonModule();
    this._InputTextModule_9 = new import10.InputTextModule();
    this._CalendarModule_10 = new import11.CalendarModule();
    this._SharedModule_11 = new import12.SharedModule();
    this._DropdownModule_12 = new import13.DropdownModule();
    this._CheckboxModule_13 = new import14.CheckboxModule();
    this._SliderModule_14 = new import15.SliderModule();
    this._InplaceModule_15 = new import16.InplaceModule();
    this._InputMaskModule_16 = new import17.InputMaskModule();
    this._TabViewModule_17 = new import18.TabViewModule();
    this._ConfirmDialogModule_18 = new import19.ConfirmDialogModule();
    this._PaginatorModule_19 = new import20.PaginatorModule();
    this._DataTableModule_20 = new import21.DataTableModule();
    this._MultiSelectModule_21 = new import22.MultiSelectModule();
    this._PanelModule_22 = new import23.PanelModule();
    this._TreeModule_23 = new import24.TreeModule();
    this._ToggleButtonModule_24 = new import25.ToggleButtonModule();
    this._InputSwitchModule_25 = new import26.InputSwitchModule();
    this._AccordionModule_26 = new import27.AccordionModule();
    this._ChipsModule_27 = new import28.ChipsModule();
    this._PrimeNgModule_28 = new import29.PrimeNgModule();
    this._CrudModule_29 = new import30.CrudModule();
    this._AppModule_30 = new import1.AppModule();
    this._ErrorHandler_33 = import4.errorHandler();
    this._ApplicationInitStatus_34 = new import32.ApplicationInitStatus(this.parent.get(import32.APP_INITIALIZER,(null as any)));
    this._Testability_35 = new import33.Testability(this.parent.get(import62.NgZone));
    this._ApplicationRef__36 = new import34.ApplicationRef_(this.parent.get(import62.NgZone),this.parent.get(import64.Console),this,this._ErrorHandler_33,this,this._ApplicationInitStatus_34,this.parent.get(import33.TestabilityRegistry,(null as any)),this._Testability_35);
    return this._AppModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_4; }
    if ((token === import6.FormsModule)) { return this._FormsModule_5; }
    if ((token === import7.HttpModule)) { return this._HttpModule_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import9.ButtonModule)) { return this._ButtonModule_8; }
    if ((token === import10.InputTextModule)) { return this._InputTextModule_9; }
    if ((token === import11.CalendarModule)) { return this._CalendarModule_10; }
    if ((token === import12.SharedModule)) { return this._SharedModule_11; }
    if ((token === import13.DropdownModule)) { return this._DropdownModule_12; }
    if ((token === import14.CheckboxModule)) { return this._CheckboxModule_13; }
    if ((token === import15.SliderModule)) { return this._SliderModule_14; }
    if ((token === import16.InplaceModule)) { return this._InplaceModule_15; }
    if ((token === import17.InputMaskModule)) { return this._InputMaskModule_16; }
    if ((token === import18.TabViewModule)) { return this._TabViewModule_17; }
    if ((token === import19.ConfirmDialogModule)) { return this._ConfirmDialogModule_18; }
    if ((token === import20.PaginatorModule)) { return this._PaginatorModule_19; }
    if ((token === import21.DataTableModule)) { return this._DataTableModule_20; }
    if ((token === import22.MultiSelectModule)) { return this._MultiSelectModule_21; }
    if ((token === import23.PanelModule)) { return this._PanelModule_22; }
    if ((token === import24.TreeModule)) { return this._TreeModule_23; }
    if ((token === import25.ToggleButtonModule)) { return this._ToggleButtonModule_24; }
    if ((token === import26.InputSwitchModule)) { return this._InputSwitchModule_25; }
    if ((token === import27.AccordionModule)) { return this._AccordionModule_26; }
    if ((token === import28.ChipsModule)) { return this._ChipsModule_27; }
    if ((token === import29.PrimeNgModule)) { return this._PrimeNgModule_28; }
    if ((token === import30.CrudModule)) { return this._CrudModule_29; }
    if ((token === import1.AppModule)) { return this._AppModule_30; }
    if ((token === import58.LOCALE_ID)) { return this._LOCALE_ID_31; }
    if ((token === import31.NgLocalization)) { return this._NgLocalization_32; }
    if ((token === import65.ErrorHandler)) { return this._ErrorHandler_33; }
    if ((token === import32.ApplicationInitStatus)) { return this._ApplicationInitStatus_34; }
    if ((token === import33.Testability)) { return this._Testability_35; }
    if ((token === import34.ApplicationRef_)) { return this._ApplicationRef__36; }
    if ((token === import34.ApplicationRef)) { return this._ApplicationRef_37; }
    if ((token === import35.Compiler)) { return this._Compiler_38; }
    if ((token === import59.APP_ID)) { return this._APP_ID_39; }
    if ((token === import66.DOCUMENT)) { return this._DOCUMENT_40; }
    if ((token === import36.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_41; }
    if ((token === import37.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_42; }
    if ((token === import37.EventManager)) { return this._EventManager_43; }
    if ((token === import38.DomSharedStylesHost)) { return this._DomSharedStylesHost_44; }
    if ((token === import67.AnimationDriver)) { return this._AnimationDriver_45; }
    if ((token === import39.DomRootRenderer)) { return this._DomRootRenderer_46; }
    if ((token === import68.RootRenderer)) { return this._RootRenderer_47; }
    if ((token === import40.DomSanitizer)) { return this._DomSanitizer_48; }
    if ((token === import69.Sanitizer)) { return this._Sanitizer_49; }
    if ((token === import41.AnimationQueue)) { return this._AnimationQueue_50; }
    if ((token === import42.ViewUtils)) { return this._ViewUtils_51; }
    if ((token === import70.IterableDiffers)) { return this._IterableDiffers_52; }
    if ((token === import71.KeyValueDiffers)) { return this._KeyValueDiffers_53; }
    if ((token === import38.SharedStylesHost)) { return this._SharedStylesHost_54; }
    if ((token === import43.Title)) { return this._Title_55; }
    if ((token === import44.FormBuilder)) { return this._FormBuilder_56; }
    if ((token === import45.RadioControlRegistry)) { return this._RadioControlRegistry_57; }
    if ((token === import46.BrowserXhr)) { return this._BrowserXhr_58; }
    if ((token === import47.ResponseOptions)) { return this._ResponseOptions_59; }
    if ((token === import72.XSRFStrategy)) { return this._XSRFStrategy_60; }
    if ((token === import48.XHRBackend)) { return this._XHRBackend_61; }
    if ((token === import49.RequestOptions)) { return this._RequestOptions_62; }
    if ((token === import73.Http)) { return this._Http_63; }
    if ((token === import50.ConfirmationService)) { return this._ConfirmationService_64; }
    if ((token === import51.Scheduling)) { return this._Scheduling_65; }
    if ((token === import52.User)) { return this._User_66; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__36.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);
export class Wrapper_App {
  /*private*/ _eventHandler:Function;
  context:import1.App;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import1.App();
  }
  ngOnDetach(view:import74.AppView<any>,componentView:import74.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import74.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import74.AppView<any>,componentView:import74.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import74.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_App_Host:import68.RenderComponentType = import42.createRenderComponentType('',0,import75.ViewEncapsulation.None,([] as any[]),{});
class View_App_Host0 extends import74.AppView<any> {
  _el_0:any;
  compView_0:import74.AppView<import1.App>;
  _App_0_3:Wrapper_App;
  constructor(viewUtils:import42.ViewUtils,parentView:import74.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_App_Host0,renderType_App_Host,import76.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import77.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import78.ComponentRef<any> {
    this._el_0 = import42.selectOrCreateRenderHostElement(this.renderer,'my-app',import42.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_App0(this.viewUtils,this,0,this._el_0);
    this._App_0_3 = new Wrapper_App();
    this.compView_0.create(this._App_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import78.ComponentRef_<any>(0,this,this._el_0,this._App_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.App) && (0 === requestNodeIndex))) { return this._App_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._App_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppNgFactory:import78.ComponentFactory<import1.App> = new import78.ComponentFactory<import1.App>('my-app',View_App_Host0,import1.App);
const styles_App:any[] = ([] as any[]);
var renderType_App:import68.RenderComponentType = import42.createRenderComponentType('',0,import75.ViewEncapsulation.None,styles_App,{});
export class View_App0 extends import74.AppView<import1.App> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  compView_3:import74.AppView<import79.CrudComponent>;
  _Service_3_3:import80.Service;
  _CrudComponent_3_4:import81.Wrapper_CrudComponent;
  _text_4:any;
  _text_5:any;
  constructor(viewUtils:import42.ViewUtils,parentView:import74.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_App0,renderType_App,import76.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import77.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import78.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import42.createRenderElement(this.renderer,parentRenderNode,'div',new import42.InlineArray2(2,'style','width: 50%;'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = import42.createRenderElement(this.renderer,this._el_1,'crud',import42.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import81.View_CrudComponent0(this.viewUtils,this,3,this._el_3);
    this._Service_3_3 = new import80.Service(this.parentView.injectorGet(import73.Http,this.parentIndex));
    this._CrudComponent_3_4 = new import81.Wrapper_CrudComponent(this._Service_3_3);
    this.compView_3.create(this._CrudComponent_3_4.context);
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import42.subscribeToRenderElement(this,this._el_3,new import42.InlineArray4(4,'onSave',(null as any),'onCancel',(null as any)),this.eventHandler(this.handleEvent_3));
    this._CrudComponent_3_4.subscribe(this,this.eventHandler(this.handleEvent_3),true,true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import80.Service) && (3 === requestNodeIndex))) { return this._Service_3_3; }
    if (((token === import79.CrudComponent) && (3 === requestNodeIndex))) { return this._CrudComponent_3_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3_0_0:any = 'Scheduling';
    this._CrudComponent_3_4.check_clazz(currVal_3_0_0,throwOnChange,false);
    this._CrudComponent_3_4.ngDoCheck(this,this._el_3,throwOnChange);
    this.compView_3.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_3.destroy();
    this._CrudComponent_3_4.ngOnDestroy();
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onSave')) {
      const pd_sub_0:any = ((<any>this.context.handleOnSave($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onCancel')) {
      const pd_sub_1:any = ((<any>this.context.handleOnCancel()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}