/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './crud.module';
import * as import2 from '@angular/forms/src/directives';
import * as import3 from '@angular/forms/src/form_providers';
import * as import4 from '@angular/http/src/http_module';
import * as import5 from '@angular/common/src/common_module';
import * as import6 from '@angular/core/src/application_module';
import * as import7 from '@angular/platform-browser/src/browser';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from 'primeng/components/button/button';
import * as import10 from 'primeng/components/inputtext/inputtext';
import * as import11 from 'primeng/components/calendar/calendar';
import * as import12 from 'primeng/components/common/shared';
import * as import13 from 'primeng/components/dropdown/dropdown';
import * as import14 from 'primeng/components/checkbox/checkbox';
import * as import15 from 'primeng/components/slider/slider';
import * as import16 from 'primeng/components/inplace/inplace';
import * as import17 from 'primeng/components/inputmask/inputmask';
import * as import18 from 'primeng/components/tabview/tabview';
import * as import19 from 'primeng/components/confirmdialog/confirmdialog';
import * as import20 from 'primeng/components/paginator/paginator';
import * as import21 from 'primeng/components/datatable/datatable';
import * as import22 from 'primeng/components/multiselect/multiselect';
import * as import23 from 'primeng/components/panel/panel';
import * as import24 from 'primeng/components/tree/tree';
import * as import25 from 'primeng/components/togglebutton/togglebutton';
import * as import26 from 'primeng/components/inputswitch/inputswitch';
import * as import27 from 'primeng/components/accordion/accordion';
import * as import28 from 'primeng/components/chips/chips';
import * as import29 from './primeng.module';
import * as import30 from 'ng2-translate/index';
import * as import31 from '@angular/forms/src/form_builder';
import * as import32 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import33 from '@angular/http/src/backends/browser_xhr';
import * as import34 from '@angular/http/src/base_response_options';
import * as import35 from '@angular/http/src/backends/xhr_backend';
import * as import36 from '@angular/http/src/base_request_options';
import * as import37 from '@angular/common/src/localization';
import * as import38 from '@angular/core/src/application_init';
import * as import39 from '@angular/core/src/testability/testability';
import * as import40 from '@angular/core/src/application_ref';
import * as import41 from '@angular/core/src/linker/compiler';
import * as import42 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import43 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import44 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import45 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import46 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import47 from '@angular/core/src/animation/animation_queue';
import * as import48 from '@angular/core/src/linker/view_utils';
import * as import49 from '@angular/platform-browser/src/browser/title';
import * as import50 from 'primeng/components/common/api';
import * as import51 from 'ng2-translate/src/translate.service';
import * as import52 from '@angular/core/src/di/injector';
import * as import53 from './components/input.component.ngfactory';
import * as import54 from './components/multiselect.component.ngfactory';
import * as import55 from './components/chips.component.ngfactory';
import * as import56 from './components/select.component.ngfactory';
import * as import57 from '@angular/core/src/i18n/tokens';
import * as import58 from '@angular/core/src/application_tokens';
import * as import59 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import60 from '@angular/platform-browser/src/dom/events/key_events';
import * as import61 from '@angular/core/src/zone/ng_zone';
import * as import62 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import63 from '@angular/core/src/console';
import * as import64 from '@angular/http/src/interfaces';
import * as import65 from '@angular/http/src/http';
import * as import66 from '@angular/core/src/error_handler';
import * as import67 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import68 from '@angular/platform-browser/src/dom/animation_driver';
import * as import69 from '@angular/core/src/render/api';
import * as import70 from '@angular/core/src/security';
import * as import71 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import72 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class CrudModuleInjector extends import0.NgModuleInjector<import1.CrudModule> {
  _InternalFormsSharedModule_0:import2.InternalFormsSharedModule;
  _ReactiveFormsModule_1:import3.ReactiveFormsModule;
  _FormsModule_2:import3.FormsModule;
  _HttpModule_3:import4.HttpModule;
  _CommonModule_4:import5.CommonModule;
  _ApplicationModule_5:import6.ApplicationModule;
  _BrowserModule_6:import7.BrowserModule;
  _RouterModule_7:import8.RouterModule;
  _ButtonModule_8:import9.ButtonModule;
  _InputTextModule_9:import10.InputTextModule;
  _CalendarModule_10:import11.CalendarModule;
  _SharedModule_11:import12.SharedModule;
  _DropdownModule_12:import13.DropdownModule;
  _CheckboxModule_13:import14.CheckboxModule;
  _SliderModule_14:import15.SliderModule;
  _InplaceModule_15:import16.InplaceModule;
  _InputMaskModule_16:import17.InputMaskModule;
  _TabViewModule_17:import18.TabViewModule;
  _ConfirmDialogModule_18:import19.ConfirmDialogModule;
  _PaginatorModule_19:import20.PaginatorModule;
  _DataTableModule_20:import21.DataTableModule;
  _MultiSelectModule_21:import22.MultiSelectModule;
  _PanelModule_22:import23.PanelModule;
  _TreeModule_23:import24.TreeModule;
  _ToggleButtonModule_24:import25.ToggleButtonModule;
  _InputSwitchModule_25:import26.InputSwitchModule;
  _AccordionModule_26:import27.AccordionModule;
  _ChipsModule_27:import28.ChipsModule;
  _PrimeNgModule_28:import29.PrimeNgModule;
  _TranslateModule_29:import30.TranslateModule;
  _CrudModule_30:import1.CrudModule;
  __FormBuilder_31:import31.FormBuilder;
  __RadioControlRegistry_32:import32.RadioControlRegistry;
  __BrowserXhr_33:import33.BrowserXhr;
  __ResponseOptions_34:import34.BaseResponseOptions;
  __XSRFStrategy_35:any;
  __XHRBackend_36:import35.XHRBackend;
  __RequestOptions_37:import36.BaseRequestOptions;
  __Http_38:any;
  __LOCALE_ID_39:any;
  __NgLocalization_40:import37.NgLocaleLocalization;
  _ErrorHandler_41:any;
  _ApplicationInitStatus_42:import38.ApplicationInitStatus;
  _Testability_43:import39.Testability;
  _ApplicationRef__44:import40.ApplicationRef_;
  __ApplicationRef_45:any;
  __Compiler_46:import41.Compiler;
  __APP_ID_47:any;
  __DOCUMENT_48:any;
  __HAMMER_GESTURE_CONFIG_49:import42.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_50:any[];
  __EventManager_51:import43.EventManager;
  __DomSharedStylesHost_52:import44.DomSharedStylesHost;
  __AnimationDriver_53:any;
  __DomRootRenderer_54:import45.DomRootRenderer_;
  __RootRenderer_55:any;
  __DomSanitizer_56:import46.DomSanitizerImpl;
  __Sanitizer_57:any;
  __AnimationQueue_58:import47.AnimationQueue;
  __ViewUtils_59:import48.ViewUtils;
  __IterableDiffers_60:any;
  __KeyValueDiffers_61:any;
  __SharedStylesHost_62:any;
  __Title_63:import49.Title;
  __ConfirmationService_64:import50.ConfirmationService;
  __TranslateLoader_65:any;
  __TranslateService_66:import51.TranslateService;
  constructor(parent:import52.Injector) {
    super(parent,[
      import53.InputTextComponentNgFactory,
      import54.MultiSelectComponentNgFactory,
      import55.ChipsComponentNgFactory,
      import56.SelectComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _FormBuilder_31():import31.FormBuilder {
    if ((this.__FormBuilder_31 == null)) { (this.__FormBuilder_31 = new import31.FormBuilder()); }
    return this.__FormBuilder_31;
  }
  get _RadioControlRegistry_32():import32.RadioControlRegistry {
    if ((this.__RadioControlRegistry_32 == null)) { (this.__RadioControlRegistry_32 = new import32.RadioControlRegistry()); }
    return this.__RadioControlRegistry_32;
  }
  get _BrowserXhr_33():import33.BrowserXhr {
    if ((this.__BrowserXhr_33 == null)) { (this.__BrowserXhr_33 = new import33.BrowserXhr()); }
    return this.__BrowserXhr_33;
  }
  get _ResponseOptions_34():import34.BaseResponseOptions {
    if ((this.__ResponseOptions_34 == null)) { (this.__ResponseOptions_34 = new import34.BaseResponseOptions()); }
    return this.__ResponseOptions_34;
  }
  get _XSRFStrategy_35():any {
    if ((this.__XSRFStrategy_35 == null)) { (this.__XSRFStrategy_35 = import4._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_35;
  }
  get _XHRBackend_36():import35.XHRBackend {
    if ((this.__XHRBackend_36 == null)) { (this.__XHRBackend_36 = new import35.XHRBackend(this._BrowserXhr_33,this._ResponseOptions_34,this._XSRFStrategy_35)); }
    return this.__XHRBackend_36;
  }
  get _RequestOptions_37():import36.BaseRequestOptions {
    if ((this.__RequestOptions_37 == null)) { (this.__RequestOptions_37 = new import36.BaseRequestOptions()); }
    return this.__RequestOptions_37;
  }
  get _Http_38():any {
    if ((this.__Http_38 == null)) { (this.__Http_38 = import4.httpFactory(this._XHRBackend_36,this._RequestOptions_37)); }
    return this.__Http_38;
  }
  get _LOCALE_ID_39():any {
    if ((this.__LOCALE_ID_39 == null)) { (this.__LOCALE_ID_39 = import6._localeFactory(this.parent.get(import57.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_39;
  }
  get _NgLocalization_40():import37.NgLocaleLocalization {
    if ((this.__NgLocalization_40 == null)) { (this.__NgLocalization_40 = new import37.NgLocaleLocalization(this._LOCALE_ID_39)); }
    return this.__NgLocalization_40;
  }
  get _ApplicationRef_45():any {
    if ((this.__ApplicationRef_45 == null)) { (this.__ApplicationRef_45 = this._ApplicationRef__44); }
    return this.__ApplicationRef_45;
  }
  get _Compiler_46():import41.Compiler {
    if ((this.__Compiler_46 == null)) { (this.__Compiler_46 = new import41.Compiler()); }
    return this.__Compiler_46;
  }
  get _APP_ID_47():any {
    if ((this.__APP_ID_47 == null)) { (this.__APP_ID_47 = import58._appIdRandomProviderFactory()); }
    return this.__APP_ID_47;
  }
  get _DOCUMENT_48():any {
    if ((this.__DOCUMENT_48 == null)) { (this.__DOCUMENT_48 = import7._document()); }
    return this.__DOCUMENT_48;
  }
  get _HAMMER_GESTURE_CONFIG_49():import42.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_49 == null)) { (this.__HAMMER_GESTURE_CONFIG_49 = new import42.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_49;
  }
  get _EVENT_MANAGER_PLUGINS_50():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_50 == null)) { (this.__EVENT_MANAGER_PLUGINS_50 = [
      new import59.DomEventsPlugin(),
      new import60.KeyEventsPlugin(),
      new import42.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_49)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_50;
  }
  get _EventManager_51():import43.EventManager {
    if ((this.__EventManager_51 == null)) { (this.__EventManager_51 = new import43.EventManager(this._EVENT_MANAGER_PLUGINS_50,this.parent.get(import61.NgZone))); }
    return this.__EventManager_51;
  }
  get _DomSharedStylesHost_52():import44.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_52 == null)) { (this.__DomSharedStylesHost_52 = new import44.DomSharedStylesHost(this._DOCUMENT_48)); }
    return this.__DomSharedStylesHost_52;
  }
  get _AnimationDriver_53():any {
    if ((this.__AnimationDriver_53 == null)) { (this.__AnimationDriver_53 = import7._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_53;
  }
  get _DomRootRenderer_54():import45.DomRootRenderer_ {
    if ((this.__DomRootRenderer_54 == null)) { (this.__DomRootRenderer_54 = new import45.DomRootRenderer_(this._DOCUMENT_48,this._EventManager_51,this._DomSharedStylesHost_52,this._AnimationDriver_53,this._APP_ID_47)); }
    return this.__DomRootRenderer_54;
  }
  get _RootRenderer_55():any {
    if ((this.__RootRenderer_55 == null)) { (this.__RootRenderer_55 = import62._createConditionalRootRenderer(this._DomRootRenderer_54,this.parent.get(import62.NgProbeToken,(null as any)),this.parent.get(import40.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_55;
  }
  get _DomSanitizer_56():import46.DomSanitizerImpl {
    if ((this.__DomSanitizer_56 == null)) { (this.__DomSanitizer_56 = new import46.DomSanitizerImpl()); }
    return this.__DomSanitizer_56;
  }
  get _Sanitizer_57():any {
    if ((this.__Sanitizer_57 == null)) { (this.__Sanitizer_57 = this._DomSanitizer_56); }
    return this.__Sanitizer_57;
  }
  get _AnimationQueue_58():import47.AnimationQueue {
    if ((this.__AnimationQueue_58 == null)) { (this.__AnimationQueue_58 = new import47.AnimationQueue(this.parent.get(import61.NgZone))); }
    return this.__AnimationQueue_58;
  }
  get _ViewUtils_59():import48.ViewUtils {
    if ((this.__ViewUtils_59 == null)) { (this.__ViewUtils_59 = new import48.ViewUtils(this._RootRenderer_55,this._Sanitizer_57,this._AnimationQueue_58)); }
    return this.__ViewUtils_59;
  }
  get _IterableDiffers_60():any {
    if ((this.__IterableDiffers_60 == null)) { (this.__IterableDiffers_60 = import6._iterableDiffersFactory()); }
    return this.__IterableDiffers_60;
  }
  get _KeyValueDiffers_61():any {
    if ((this.__KeyValueDiffers_61 == null)) { (this.__KeyValueDiffers_61 = import6._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_61;
  }
  get _SharedStylesHost_62():any {
    if ((this.__SharedStylesHost_62 == null)) { (this.__SharedStylesHost_62 = this._DomSharedStylesHost_52); }
    return this.__SharedStylesHost_62;
  }
  get _Title_63():import49.Title {
    if ((this.__Title_63 == null)) { (this.__Title_63 = new import49.Title()); }
    return this.__Title_63;
  }
  get _ConfirmationService_64():import50.ConfirmationService {
    if ((this.__ConfirmationService_64 == null)) { (this.__ConfirmationService_64 = new import50.ConfirmationService()); }
    return this.__ConfirmationService_64;
  }
  get _TranslateLoader_65():any {
    if ((this.__TranslateLoader_65 == null)) { (this.__TranslateLoader_65 = import1.createTranslateLoader(this._Http_38)); }
    return this.__TranslateLoader_65;
  }
  get _TranslateService_66():import51.TranslateService {
    if ((this.__TranslateService_66 == null)) { (this.__TranslateService_66 = new import51.TranslateService(this._TranslateLoader_65,this.parent.get(import51.MissingTranslationHandler,(null as any)))); }
    return this.__TranslateService_66;
  }
  createInternal():import1.CrudModule {
    this._InternalFormsSharedModule_0 = new import2.InternalFormsSharedModule();
    this._ReactiveFormsModule_1 = new import3.ReactiveFormsModule();
    this._FormsModule_2 = new import3.FormsModule();
    this._HttpModule_3 = new import4.HttpModule();
    this._CommonModule_4 = new import5.CommonModule();
    this._ApplicationModule_5 = new import6.ApplicationModule();
    this._BrowserModule_6 = new import7.BrowserModule(this.parent.get(import7.BrowserModule,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this.parent.get(import8.ROUTER_FORROOT_GUARD,(null as any)));
    this._ButtonModule_8 = new import9.ButtonModule();
    this._InputTextModule_9 = new import10.InputTextModule();
    this._CalendarModule_10 = new import11.CalendarModule();
    this._SharedModule_11 = new import12.SharedModule();
    this._DropdownModule_12 = new import13.DropdownModule();
    this._CheckboxModule_13 = new import14.CheckboxModule();
    this._SliderModule_14 = new import15.SliderModule();
    this._InplaceModule_15 = new import16.InplaceModule();
    this._InputMaskModule_16 = new import17.InputMaskModule();
    this._TabViewModule_17 = new import18.TabViewModule();
    this._ConfirmDialogModule_18 = new import19.ConfirmDialogModule();
    this._PaginatorModule_19 = new import20.PaginatorModule();
    this._DataTableModule_20 = new import21.DataTableModule();
    this._MultiSelectModule_21 = new import22.MultiSelectModule();
    this._PanelModule_22 = new import23.PanelModule();
    this._TreeModule_23 = new import24.TreeModule();
    this._ToggleButtonModule_24 = new import25.ToggleButtonModule();
    this._InputSwitchModule_25 = new import26.InputSwitchModule();
    this._AccordionModule_26 = new import27.AccordionModule();
    this._ChipsModule_27 = new import28.ChipsModule();
    this._PrimeNgModule_28 = new import29.PrimeNgModule();
    this._TranslateModule_29 = new import30.TranslateModule();
    this._CrudModule_30 = new import1.CrudModule();
    this._ErrorHandler_41 = import7.errorHandler();
    this._ApplicationInitStatus_42 = new import38.ApplicationInitStatus(this.parent.get(import38.APP_INITIALIZER,(null as any)));
    this._Testability_43 = new import39.Testability(this.parent.get(import61.NgZone));
    this._ApplicationRef__44 = new import40.ApplicationRef_(this.parent.get(import61.NgZone),this.parent.get(import63.Console),this,this._ErrorHandler_41,this,this._ApplicationInitStatus_42,this.parent.get(import39.TestabilityRegistry,(null as any)),this._Testability_43);
    return this._CrudModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_0; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.HttpModule)) { return this._HttpModule_3; }
    if ((token === import5.CommonModule)) { return this._CommonModule_4; }
    if ((token === import6.ApplicationModule)) { return this._ApplicationModule_5; }
    if ((token === import7.BrowserModule)) { return this._BrowserModule_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import9.ButtonModule)) { return this._ButtonModule_8; }
    if ((token === import10.InputTextModule)) { return this._InputTextModule_9; }
    if ((token === import11.CalendarModule)) { return this._CalendarModule_10; }
    if ((token === import12.SharedModule)) { return this._SharedModule_11; }
    if ((token === import13.DropdownModule)) { return this._DropdownModule_12; }
    if ((token === import14.CheckboxModule)) { return this._CheckboxModule_13; }
    if ((token === import15.SliderModule)) { return this._SliderModule_14; }
    if ((token === import16.InplaceModule)) { return this._InplaceModule_15; }
    if ((token === import17.InputMaskModule)) { return this._InputMaskModule_16; }
    if ((token === import18.TabViewModule)) { return this._TabViewModule_17; }
    if ((token === import19.ConfirmDialogModule)) { return this._ConfirmDialogModule_18; }
    if ((token === import20.PaginatorModule)) { return this._PaginatorModule_19; }
    if ((token === import21.DataTableModule)) { return this._DataTableModule_20; }
    if ((token === import22.MultiSelectModule)) { return this._MultiSelectModule_21; }
    if ((token === import23.PanelModule)) { return this._PanelModule_22; }
    if ((token === import24.TreeModule)) { return this._TreeModule_23; }
    if ((token === import25.ToggleButtonModule)) { return this._ToggleButtonModule_24; }
    if ((token === import26.InputSwitchModule)) { return this._InputSwitchModule_25; }
    if ((token === import27.AccordionModule)) { return this._AccordionModule_26; }
    if ((token === import28.ChipsModule)) { return this._ChipsModule_27; }
    if ((token === import29.PrimeNgModule)) { return this._PrimeNgModule_28; }
    if ((token === import30.TranslateModule)) { return this._TranslateModule_29; }
    if ((token === import1.CrudModule)) { return this._CrudModule_30; }
    if ((token === import31.FormBuilder)) { return this._FormBuilder_31; }
    if ((token === import32.RadioControlRegistry)) { return this._RadioControlRegistry_32; }
    if ((token === import33.BrowserXhr)) { return this._BrowserXhr_33; }
    if ((token === import34.ResponseOptions)) { return this._ResponseOptions_34; }
    if ((token === import64.XSRFStrategy)) { return this._XSRFStrategy_35; }
    if ((token === import35.XHRBackend)) { return this._XHRBackend_36; }
    if ((token === import36.RequestOptions)) { return this._RequestOptions_37; }
    if ((token === import65.Http)) { return this._Http_38; }
    if ((token === import57.LOCALE_ID)) { return this._LOCALE_ID_39; }
    if ((token === import37.NgLocalization)) { return this._NgLocalization_40; }
    if ((token === import66.ErrorHandler)) { return this._ErrorHandler_41; }
    if ((token === import38.ApplicationInitStatus)) { return this._ApplicationInitStatus_42; }
    if ((token === import39.Testability)) { return this._Testability_43; }
    if ((token === import40.ApplicationRef_)) { return this._ApplicationRef__44; }
    if ((token === import40.ApplicationRef)) { return this._ApplicationRef_45; }
    if ((token === import41.Compiler)) { return this._Compiler_46; }
    if ((token === import58.APP_ID)) { return this._APP_ID_47; }
    if ((token === import67.DOCUMENT)) { return this._DOCUMENT_48; }
    if ((token === import42.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_49; }
    if ((token === import43.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_50; }
    if ((token === import43.EventManager)) { return this._EventManager_51; }
    if ((token === import44.DomSharedStylesHost)) { return this._DomSharedStylesHost_52; }
    if ((token === import68.AnimationDriver)) { return this._AnimationDriver_53; }
    if ((token === import45.DomRootRenderer)) { return this._DomRootRenderer_54; }
    if ((token === import69.RootRenderer)) { return this._RootRenderer_55; }
    if ((token === import46.DomSanitizer)) { return this._DomSanitizer_56; }
    if ((token === import70.Sanitizer)) { return this._Sanitizer_57; }
    if ((token === import47.AnimationQueue)) { return this._AnimationQueue_58; }
    if ((token === import48.ViewUtils)) { return this._ViewUtils_59; }
    if ((token === import71.IterableDiffers)) { return this._IterableDiffers_60; }
    if ((token === import72.KeyValueDiffers)) { return this._KeyValueDiffers_61; }
    if ((token === import44.SharedStylesHost)) { return this._SharedStylesHost_62; }
    if ((token === import49.Title)) { return this._Title_63; }
    if ((token === import50.ConfirmationService)) { return this._ConfirmationService_64; }
    if ((token === import51.TranslateLoader)) { return this._TranslateLoader_65; }
    if ((token === import51.TranslateService)) { return this._TranslateService_66; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__44.ngOnDestroy();
  }
}
export const CrudModuleNgFactory:import0.NgModuleFactory<import1.CrudModule> = new import0.NgModuleFactory(CrudModuleInjector,import1.CrudModule);