/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './crud.module';
import * as import2 from '@angular/http/src/http_module';
import * as import3 from '@angular/common/src/common_module';
import * as import4 from '@angular/core/src/application_module';
import * as import5 from '@angular/platform-browser/src/browser';
import * as import6 from '@angular/router/src/router_module';
import * as import7 from 'primeng/components/button/button';
import * as import8 from 'primeng/components/inputtext/inputtext';
import * as import9 from 'primeng/components/calendar/calendar';
import * as import10 from 'primeng/components/common/shared';
import * as import11 from 'primeng/components/dropdown/dropdown';
import * as import12 from 'primeng/components/checkbox/checkbox';
import * as import13 from 'primeng/components/slider/slider';
import * as import14 from 'primeng/components/inplace/inplace';
import * as import15 from 'primeng/components/inputmask/inputmask';
import * as import16 from 'primeng/components/tabview/tabview';
import * as import17 from 'primeng/components/confirmdialog/confirmdialog';
import * as import18 from 'primeng/components/paginator/paginator';
import * as import19 from '@angular/forms/src/directives';
import * as import20 from '@angular/forms/src/form_providers';
import * as import21 from 'primeng/components/datatable/datatable';
import * as import22 from 'primeng/components/multiselect/multiselect';
import * as import23 from 'primeng/components/panel/panel';
import * as import24 from 'primeng/components/tree/tree';
import * as import25 from 'primeng/components/togglebutton/togglebutton';
import * as import26 from 'primeng/components/inputswitch/inputswitch';
import * as import27 from 'primeng/components/accordion/accordion';
import * as import28 from 'primeng/components/chips/chips';
import * as import29 from './primeng.module';
import * as import30 from '@angular/http/src/backends/browser_xhr';
import * as import31 from '@angular/http/src/base_response_options';
import * as import32 from '@angular/http/src/backends/xhr_backend';
import * as import33 from '@angular/http/src/base_request_options';
import * as import34 from '@angular/common/src/localization';
import * as import35 from '@angular/core/src/application_init';
import * as import36 from '@angular/core/src/testability/testability';
import * as import37 from '@angular/core/src/application_ref';
import * as import38 from '@angular/core/src/linker/compiler';
import * as import39 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import40 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import41 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import42 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import43 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import44 from '@angular/core/src/animation/animation_queue';
import * as import45 from '@angular/core/src/linker/view_utils';
import * as import46 from '@angular/platform-browser/src/browser/title';
import * as import47 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import48 from 'primeng/components/common/api';
import * as import49 from '@angular/core/src/di/injector';
import * as import50 from './components/input.component.ngfactory';
import * as import51 from './components/multiselect.component.ngfactory';
import * as import52 from './components/chips.component.ngfactory';
import * as import53 from '@angular/core/src/i18n/tokens';
import * as import54 from '@angular/core/src/application_tokens';
import * as import55 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import56 from '@angular/platform-browser/src/dom/events/key_events';
import * as import57 from '@angular/core/src/zone/ng_zone';
import * as import58 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import59 from '@angular/core/src/console';
import * as import60 from '@angular/http/src/interfaces';
import * as import61 from '@angular/http/src/http';
import * as import62 from '@angular/core/src/error_handler';
import * as import63 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import64 from '@angular/platform-browser/src/dom/animation_driver';
import * as import65 from '@angular/core/src/render/api';
import * as import66 from '@angular/core/src/security';
import * as import67 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import68 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class CrudModuleInjector extends import0.NgModuleInjector<import1.CrudModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _ApplicationModule_2:import4.ApplicationModule;
  _BrowserModule_3:import5.BrowserModule;
  _RouterModule_4:import6.RouterModule;
  _ButtonModule_5:import7.ButtonModule;
  _InputTextModule_6:import8.InputTextModule;
  _CalendarModule_7:import9.CalendarModule;
  _SharedModule_8:import10.SharedModule;
  _DropdownModule_9:import11.DropdownModule;
  _CheckboxModule_10:import12.CheckboxModule;
  _SliderModule_11:import13.SliderModule;
  _InplaceModule_12:import14.InplaceModule;
  _InputMaskModule_13:import15.InputMaskModule;
  _TabViewModule_14:import16.TabViewModule;
  _ConfirmDialogModule_15:import17.ConfirmDialogModule;
  _PaginatorModule_16:import18.PaginatorModule;
  _InternalFormsSharedModule_17:import19.InternalFormsSharedModule;
  _FormsModule_18:import20.FormsModule;
  _DataTableModule_19:import21.DataTableModule;
  _MultiSelectModule_20:import22.MultiSelectModule;
  _PanelModule_21:import23.PanelModule;
  _TreeModule_22:import24.TreeModule;
  _ToggleButtonModule_23:import25.ToggleButtonModule;
  _InputSwitchModule_24:import26.InputSwitchModule;
  _AccordionModule_25:import27.AccordionModule;
  _ChipsModule_26:import28.ChipsModule;
  _PrimeNgModule_27:import29.PrimeNgModule;
  _CrudModule_28:import1.CrudModule;
  __BrowserXhr_29:import30.BrowserXhr;
  __ResponseOptions_30:import31.BaseResponseOptions;
  __XSRFStrategy_31:any;
  __XHRBackend_32:import32.XHRBackend;
  __RequestOptions_33:import33.BaseRequestOptions;
  __Http_34:any;
  __LOCALE_ID_35:any;
  __NgLocalization_36:import34.NgLocaleLocalization;
  _ErrorHandler_37:any;
  _ApplicationInitStatus_38:import35.ApplicationInitStatus;
  _Testability_39:import36.Testability;
  _ApplicationRef__40:import37.ApplicationRef_;
  __ApplicationRef_41:any;
  __Compiler_42:import38.Compiler;
  __APP_ID_43:any;
  __DOCUMENT_44:any;
  __HAMMER_GESTURE_CONFIG_45:import39.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_46:any[];
  __EventManager_47:import40.EventManager;
  __DomSharedStylesHost_48:import41.DomSharedStylesHost;
  __AnimationDriver_49:any;
  __DomRootRenderer_50:import42.DomRootRenderer_;
  __RootRenderer_51:any;
  __DomSanitizer_52:import43.DomSanitizerImpl;
  __Sanitizer_53:any;
  __AnimationQueue_54:import44.AnimationQueue;
  __ViewUtils_55:import45.ViewUtils;
  __IterableDiffers_56:any;
  __KeyValueDiffers_57:any;
  __SharedStylesHost_58:any;
  __Title_59:import46.Title;
  __RadioControlRegistry_60:import47.RadioControlRegistry;
  __ConfirmationService_61:import48.ConfirmationService;
  constructor(parent:import49.Injector) {
    super(parent,[
      import50.InputTextComponentNgFactory,
      import51.MultiSelectComponentNgFactory,
      import52.ChipsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _BrowserXhr_29():import30.BrowserXhr {
    if ((this.__BrowserXhr_29 == null)) { (this.__BrowserXhr_29 = new import30.BrowserXhr()); }
    return this.__BrowserXhr_29;
  }
  get _ResponseOptions_30():import31.BaseResponseOptions {
    if ((this.__ResponseOptions_30 == null)) { (this.__ResponseOptions_30 = new import31.BaseResponseOptions()); }
    return this.__ResponseOptions_30;
  }
  get _XSRFStrategy_31():any {
    if ((this.__XSRFStrategy_31 == null)) { (this.__XSRFStrategy_31 = import2._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_31;
  }
  get _XHRBackend_32():import32.XHRBackend {
    if ((this.__XHRBackend_32 == null)) { (this.__XHRBackend_32 = new import32.XHRBackend(this._BrowserXhr_29,this._ResponseOptions_30,this._XSRFStrategy_31)); }
    return this.__XHRBackend_32;
  }
  get _RequestOptions_33():import33.BaseRequestOptions {
    if ((this.__RequestOptions_33 == null)) { (this.__RequestOptions_33 = new import33.BaseRequestOptions()); }
    return this.__RequestOptions_33;
  }
  get _Http_34():any {
    if ((this.__Http_34 == null)) { (this.__Http_34 = import2.httpFactory(this._XHRBackend_32,this._RequestOptions_33)); }
    return this.__Http_34;
  }
  get _LOCALE_ID_35():any {
    if ((this.__LOCALE_ID_35 == null)) { (this.__LOCALE_ID_35 = import4._localeFactory(this.parent.get(import53.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_35;
  }
  get _NgLocalization_36():import34.NgLocaleLocalization {
    if ((this.__NgLocalization_36 == null)) { (this.__NgLocalization_36 = new import34.NgLocaleLocalization(this._LOCALE_ID_35)); }
    return this.__NgLocalization_36;
  }
  get _ApplicationRef_41():any {
    if ((this.__ApplicationRef_41 == null)) { (this.__ApplicationRef_41 = this._ApplicationRef__40); }
    return this.__ApplicationRef_41;
  }
  get _Compiler_42():import38.Compiler {
    if ((this.__Compiler_42 == null)) { (this.__Compiler_42 = new import38.Compiler()); }
    return this.__Compiler_42;
  }
  get _APP_ID_43():any {
    if ((this.__APP_ID_43 == null)) { (this.__APP_ID_43 = import54._appIdRandomProviderFactory()); }
    return this.__APP_ID_43;
  }
  get _DOCUMENT_44():any {
    if ((this.__DOCUMENT_44 == null)) { (this.__DOCUMENT_44 = import5._document()); }
    return this.__DOCUMENT_44;
  }
  get _HAMMER_GESTURE_CONFIG_45():import39.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_45 == null)) { (this.__HAMMER_GESTURE_CONFIG_45 = new import39.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_45;
  }
  get _EVENT_MANAGER_PLUGINS_46():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_46 == null)) { (this.__EVENT_MANAGER_PLUGINS_46 = [
      new import55.DomEventsPlugin(),
      new import56.KeyEventsPlugin(),
      new import39.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_45)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_46;
  }
  get _EventManager_47():import40.EventManager {
    if ((this.__EventManager_47 == null)) { (this.__EventManager_47 = new import40.EventManager(this._EVENT_MANAGER_PLUGINS_46,this.parent.get(import57.NgZone))); }
    return this.__EventManager_47;
  }
  get _DomSharedStylesHost_48():import41.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_48 == null)) { (this.__DomSharedStylesHost_48 = new import41.DomSharedStylesHost(this._DOCUMENT_44)); }
    return this.__DomSharedStylesHost_48;
  }
  get _AnimationDriver_49():any {
    if ((this.__AnimationDriver_49 == null)) { (this.__AnimationDriver_49 = import5._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_49;
  }
  get _DomRootRenderer_50():import42.DomRootRenderer_ {
    if ((this.__DomRootRenderer_50 == null)) { (this.__DomRootRenderer_50 = new import42.DomRootRenderer_(this._DOCUMENT_44,this._EventManager_47,this._DomSharedStylesHost_48,this._AnimationDriver_49,this._APP_ID_43)); }
    return this.__DomRootRenderer_50;
  }
  get _RootRenderer_51():any {
    if ((this.__RootRenderer_51 == null)) { (this.__RootRenderer_51 = import58._createConditionalRootRenderer(this._DomRootRenderer_50,this.parent.get(import58.NgProbeToken,(null as any)),this.parent.get(import37.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_51;
  }
  get _DomSanitizer_52():import43.DomSanitizerImpl {
    if ((this.__DomSanitizer_52 == null)) { (this.__DomSanitizer_52 = new import43.DomSanitizerImpl()); }
    return this.__DomSanitizer_52;
  }
  get _Sanitizer_53():any {
    if ((this.__Sanitizer_53 == null)) { (this.__Sanitizer_53 = this._DomSanitizer_52); }
    return this.__Sanitizer_53;
  }
  get _AnimationQueue_54():import44.AnimationQueue {
    if ((this.__AnimationQueue_54 == null)) { (this.__AnimationQueue_54 = new import44.AnimationQueue(this.parent.get(import57.NgZone))); }
    return this.__AnimationQueue_54;
  }
  get _ViewUtils_55():import45.ViewUtils {
    if ((this.__ViewUtils_55 == null)) { (this.__ViewUtils_55 = new import45.ViewUtils(this._RootRenderer_51,this._Sanitizer_53,this._AnimationQueue_54)); }
    return this.__ViewUtils_55;
  }
  get _IterableDiffers_56():any {
    if ((this.__IterableDiffers_56 == null)) { (this.__IterableDiffers_56 = import4._iterableDiffersFactory()); }
    return this.__IterableDiffers_56;
  }
  get _KeyValueDiffers_57():any {
    if ((this.__KeyValueDiffers_57 == null)) { (this.__KeyValueDiffers_57 = import4._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_57;
  }
  get _SharedStylesHost_58():any {
    if ((this.__SharedStylesHost_58 == null)) { (this.__SharedStylesHost_58 = this._DomSharedStylesHost_48); }
    return this.__SharedStylesHost_58;
  }
  get _Title_59():import46.Title {
    if ((this.__Title_59 == null)) { (this.__Title_59 = new import46.Title()); }
    return this.__Title_59;
  }
  get _RadioControlRegistry_60():import47.RadioControlRegistry {
    if ((this.__RadioControlRegistry_60 == null)) { (this.__RadioControlRegistry_60 = new import47.RadioControlRegistry()); }
    return this.__RadioControlRegistry_60;
  }
  get _ConfirmationService_61():import48.ConfirmationService {
    if ((this.__ConfirmationService_61 == null)) { (this.__ConfirmationService_61 = new import48.ConfirmationService()); }
    return this.__ConfirmationService_61;
  }
  createInternal():import1.CrudModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._ApplicationModule_2 = new import4.ApplicationModule();
    this._BrowserModule_3 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._RouterModule_4 = new import6.RouterModule(this.parent.get(import6.ROUTER_FORROOT_GUARD,(null as any)));
    this._ButtonModule_5 = new import7.ButtonModule();
    this._InputTextModule_6 = new import8.InputTextModule();
    this._CalendarModule_7 = new import9.CalendarModule();
    this._SharedModule_8 = new import10.SharedModule();
    this._DropdownModule_9 = new import11.DropdownModule();
    this._CheckboxModule_10 = new import12.CheckboxModule();
    this._SliderModule_11 = new import13.SliderModule();
    this._InplaceModule_12 = new import14.InplaceModule();
    this._InputMaskModule_13 = new import15.InputMaskModule();
    this._TabViewModule_14 = new import16.TabViewModule();
    this._ConfirmDialogModule_15 = new import17.ConfirmDialogModule();
    this._PaginatorModule_16 = new import18.PaginatorModule();
    this._InternalFormsSharedModule_17 = new import19.InternalFormsSharedModule();
    this._FormsModule_18 = new import20.FormsModule();
    this._DataTableModule_19 = new import21.DataTableModule();
    this._MultiSelectModule_20 = new import22.MultiSelectModule();
    this._PanelModule_21 = new import23.PanelModule();
    this._TreeModule_22 = new import24.TreeModule();
    this._ToggleButtonModule_23 = new import25.ToggleButtonModule();
    this._InputSwitchModule_24 = new import26.InputSwitchModule();
    this._AccordionModule_25 = new import27.AccordionModule();
    this._ChipsModule_26 = new import28.ChipsModule();
    this._PrimeNgModule_27 = new import29.PrimeNgModule();
    this._CrudModule_28 = new import1.CrudModule();
    this._ErrorHandler_37 = import5.errorHandler();
    this._ApplicationInitStatus_38 = new import35.ApplicationInitStatus(this.parent.get(import35.APP_INITIALIZER,(null as any)));
    this._Testability_39 = new import36.Testability(this.parent.get(import57.NgZone));
    this._ApplicationRef__40 = new import37.ApplicationRef_(this.parent.get(import57.NgZone),this.parent.get(import59.Console),this,this._ErrorHandler_37,this,this._ApplicationInitStatus_38,this.parent.get(import36.TestabilityRegistry,(null as any)),this._Testability_39);
    return this._CrudModule_28;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import4.ApplicationModule)) { return this._ApplicationModule_2; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_3; }
    if ((token === import6.RouterModule)) { return this._RouterModule_4; }
    if ((token === import7.ButtonModule)) { return this._ButtonModule_5; }
    if ((token === import8.InputTextModule)) { return this._InputTextModule_6; }
    if ((token === import9.CalendarModule)) { return this._CalendarModule_7; }
    if ((token === import10.SharedModule)) { return this._SharedModule_8; }
    if ((token === import11.DropdownModule)) { return this._DropdownModule_9; }
    if ((token === import12.CheckboxModule)) { return this._CheckboxModule_10; }
    if ((token === import13.SliderModule)) { return this._SliderModule_11; }
    if ((token === import14.InplaceModule)) { return this._InplaceModule_12; }
    if ((token === import15.InputMaskModule)) { return this._InputMaskModule_13; }
    if ((token === import16.TabViewModule)) { return this._TabViewModule_14; }
    if ((token === import17.ConfirmDialogModule)) { return this._ConfirmDialogModule_15; }
    if ((token === import18.PaginatorModule)) { return this._PaginatorModule_16; }
    if ((token === import19.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_17; }
    if ((token === import20.FormsModule)) { return this._FormsModule_18; }
    if ((token === import21.DataTableModule)) { return this._DataTableModule_19; }
    if ((token === import22.MultiSelectModule)) { return this._MultiSelectModule_20; }
    if ((token === import23.PanelModule)) { return this._PanelModule_21; }
    if ((token === import24.TreeModule)) { return this._TreeModule_22; }
    if ((token === import25.ToggleButtonModule)) { return this._ToggleButtonModule_23; }
    if ((token === import26.InputSwitchModule)) { return this._InputSwitchModule_24; }
    if ((token === import27.AccordionModule)) { return this._AccordionModule_25; }
    if ((token === import28.ChipsModule)) { return this._ChipsModule_26; }
    if ((token === import29.PrimeNgModule)) { return this._PrimeNgModule_27; }
    if ((token === import1.CrudModule)) { return this._CrudModule_28; }
    if ((token === import30.BrowserXhr)) { return this._BrowserXhr_29; }
    if ((token === import31.ResponseOptions)) { return this._ResponseOptions_30; }
    if ((token === import60.XSRFStrategy)) { return this._XSRFStrategy_31; }
    if ((token === import32.XHRBackend)) { return this._XHRBackend_32; }
    if ((token === import33.RequestOptions)) { return this._RequestOptions_33; }
    if ((token === import61.Http)) { return this._Http_34; }
    if ((token === import53.LOCALE_ID)) { return this._LOCALE_ID_35; }
    if ((token === import34.NgLocalization)) { return this._NgLocalization_36; }
    if ((token === import62.ErrorHandler)) { return this._ErrorHandler_37; }
    if ((token === import35.ApplicationInitStatus)) { return this._ApplicationInitStatus_38; }
    if ((token === import36.Testability)) { return this._Testability_39; }
    if ((token === import37.ApplicationRef_)) { return this._ApplicationRef__40; }
    if ((token === import37.ApplicationRef)) { return this._ApplicationRef_41; }
    if ((token === import38.Compiler)) { return this._Compiler_42; }
    if ((token === import54.APP_ID)) { return this._APP_ID_43; }
    if ((token === import63.DOCUMENT)) { return this._DOCUMENT_44; }
    if ((token === import39.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_45; }
    if ((token === import40.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_46; }
    if ((token === import40.EventManager)) { return this._EventManager_47; }
    if ((token === import41.DomSharedStylesHost)) { return this._DomSharedStylesHost_48; }
    if ((token === import64.AnimationDriver)) { return this._AnimationDriver_49; }
    if ((token === import42.DomRootRenderer)) { return this._DomRootRenderer_50; }
    if ((token === import65.RootRenderer)) { return this._RootRenderer_51; }
    if ((token === import43.DomSanitizer)) { return this._DomSanitizer_52; }
    if ((token === import66.Sanitizer)) { return this._Sanitizer_53; }
    if ((token === import44.AnimationQueue)) { return this._AnimationQueue_54; }
    if ((token === import45.ViewUtils)) { return this._ViewUtils_55; }
    if ((token === import67.IterableDiffers)) { return this._IterableDiffers_56; }
    if ((token === import68.KeyValueDiffers)) { return this._KeyValueDiffers_57; }
    if ((token === import41.SharedStylesHost)) { return this._SharedStylesHost_58; }
    if ((token === import46.Title)) { return this._Title_59; }
    if ((token === import47.RadioControlRegistry)) { return this._RadioControlRegistry_60; }
    if ((token === import48.ConfirmationService)) { return this._ConfirmationService_61; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__40.ngOnDestroy();
  }
}
export const CrudModuleNgFactory:import0.NgModuleFactory<import1.CrudModule> = new import0.NgModuleFactory(CrudModuleInjector,import1.CrudModule);